image: ubuntu:latest

before_script:
  - apt-get -yq update
  - apt-get -yq update
  - apt-get -yq install python3.6 python3-pip
  - apt-get -yq install ruby-full
  - pip install gcovr --break-system-packages
  - gem install ceedling
  - ceedling version
  - gcov --version
  - gcovr --version

test_static:
   stage: test
   script:
      - cd test
      - ceedling clean
      - ceedling test:all gcov:all --verbosity=7 --mixin=options/static.yml 

   artifacts:
    paths:
      - test/build/*
test_static_periodic_tick:
   stage: test
   script:
      - cd test
      - ceedling clean
      - ceedling test:all gcov:all --verbosity=7 --mixin=options/static_periodic_tick.yml      
   artifacts:
    paths:
      - test/build/*
test_dynamic:
   stage: test
   script:
      - cd test
      - ceedling clean
      - ceedling test:all gcov:all --verbosity=7 --mixin=options/dynamic.yml 
   artifacts:
    paths:
      - test/build/*


      