image: ubuntu:latest

before_script:
  - apt-get -yq update  
  - apt-get -yq install python3.6 python3-pip
  - apt-get -yq install ruby-full
  - pip install gcovr --break-system-packages
  - gem install ceedling
  - ceedling version
  - gcov --version
  - gcovr --version

unit_test_static:
   stage: test
   script:
      - cd test
      - ceedling clean --project=unit_tests.yml
      - ceedling test:all gcov:all --project=unit_tests.yml --verbosity=7 --mixin=options/static.yml 

   artifacts:
    paths:
      - test/build/*

unit_test_static_periodic_tick:
   stage: test
   script:
      - cd test
      - ceedling clean --project=unit_tests.yml
      - ceedling test:all gcov:all --project=unit_tests.yml --verbosity=7 --mixin=options/static_periodic_tick.yml      
   artifacts:
    paths:
      - test/build/*

unit_test_dynamic:
   stage: test
   script:
      - cd test
      - ceedling clean --project=unit_tests.yml
      - ceedling test:all gcov:all --project=unit_tests.yml --verbosity=7 --mixin=options/dynamic.yml 
   artifacts:
    paths:
      - test/build/*

test_cmake:
  stage: test
  script:
    - apt-get update && apt-get -yq install cmake
    - cd test/test_cmake
    - mkdir -p build && cd build
    - cmake ..
    - make    
    - ctest --output-on-failure
  artifacts:
    paths:
      - cmake_program/build/*



      